/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ur_5_constr_h_e_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[70] = {66, 1, 0, 66, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};

/* ur_5_constr_h_e_fun_jac_uxt_zt:(i0[6],i1[66])->(o0,o1[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=6.8442800000000005e+01;
  a1=arg[0] ? arg[0][0] : 0;
  a2=arg[1] ? arg[1][59] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a1=(a1-a2);
  a2=(a3*a1);
  a4=arg[0] ? arg[0][1] : 0;
  a5=arg[1] ? arg[1][60] : 0;
  a6=(a4-a5);
  a6=(a0*a6);
  a4=(a4-a5);
  a5=(a6*a4);
  a2=(a2+a5);
  a5=arg[0] ? arg[0][2] : 0;
  a7=arg[1] ? arg[1][61] : 0;
  a8=(a5-a7);
  a8=(a0*a8);
  a5=(a5-a7);
  a7=(a8*a5);
  a2=(a2+a7);
  a7=arg[0] ? arg[0][3] : 0;
  a9=arg[1] ? arg[1][62] : 0;
  a10=(a7-a9);
  a10=(a0*a10);
  a7=(a7-a9);
  a9=(a10*a7);
  a2=(a2+a9);
  a9=arg[0] ? arg[0][4] : 0;
  a11=arg[1] ? arg[1][63] : 0;
  a12=(a9-a11);
  a12=(a0*a12);
  a9=(a9-a11);
  a11=(a12*a9);
  a2=(a2+a11);
  a11=arg[0] ? arg[0][5] : 0;
  a13=arg[1] ? arg[1][64] : 0;
  a14=(a11-a13);
  a14=(a0*a14);
  a11=(a11-a13);
  a13=(a14*a11);
  a2=(a2+a13);
  a13=arg[1] ? arg[1][65] : 0;
  a2=(a2-a13);
  if (res[0]!=0) res[0][0]=a2;
  a1=(a0*a1);
  a3=(a3+a1);
  if (res[1]!=0) res[1][0]=a3;
  a4=(a0*a4);
  a6=(a6+a4);
  if (res[1]!=0) res[1][1]=a6;
  a5=(a0*a5);
  a8=(a8+a5);
  if (res[1]!=0) res[1][2]=a8;
  a7=(a0*a7);
  a10=(a10+a7);
  if (res[1]!=0) res[1][3]=a10;
  a9=(a0*a9);
  a12=(a12+a9);
  if (res[1]!=0) res[1][4]=a12;
  a0=(a0*a11);
  a14=(a14+a0);
  if (res[1]!=0) res[1][5]=a14;
  return 0;
}

CASADI_SYMBOL_EXPORT int ur_5_constr_h_e_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void ur_5_constr_h_e_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void ur_5_constr_h_e_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ur_5_constr_h_e_fun_jac_uxt_zt_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int ur_5_constr_h_e_fun_jac_uxt_zt_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* ur_5_constr_h_e_fun_jac_uxt_zt_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ur_5_constr_h_e_fun_jac_uxt_zt_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ur_5_constr_h_e_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ur_5_constr_h_e_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ur_5_constr_h_e_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
